services:
  postgres:
    image: postgres:17
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes: 
      - ./server/database.sql:/docker-entrypoint-initdb.d/database.sql
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  node:
    build: ./server
    ports: 
      - "5000:5000"
    command: "node index.js"
    depends_on:
      - postgres
  react:
    build: ./client
    ports: 
      - "3000:3000"
    command: "npm start"
    depends_on:
      - node
    develop:
      watch:
      - action: sync
        path: ./client
        target: /app
        ignore:
          - node_modules/
      - action: rebuild
        path: package.json
volumes:
  postgres_data: